/**
 * AI Artwork Description Generator Types
 * Used for OpenAI GPT-4o Vision integration and DeepL translation
 */

/**
 * Metadata about an artwork used for context in AI generation
 */
export interface ArtworkMetadata {
  title?: string
  year?: number | null
  medium?: string | null
  dimensions?: string | null
  series?: string | null
}

/**
 * Content generated by the AI for an artwork description
 */
export interface GeneratedContent {
  /** 150-200 word exhibition-quality description */
  description: string
  /** 50-word preview for gallery cards */
  short_description: string
  /** SEO-optimized title (max 60 chars) */
  seo_title: string
  /** Accessibility description for screen readers (max 125 chars) */
  alt_text: string
  /** 5-8 suggested tags for categorization */
  suggested_tags: string[]
  /** Confidence score 0.0-1.0 based on image quality and metadata */
  confidence_score: number
}

/**
 * Translated content for a specific language
 */
export interface TranslatedContent {
  description: string
  short_description: string
  seo_title: string
  alt_text: string
}

/**
 * Complete generation result with translations and usage metrics
 */
export interface GenerationResult extends GeneratedContent {
  /** Translations for French and Japanese */
  translations: {
    fr: TranslatedContent
    ja: TranslatedContent
  }
  /** Total tokens used (input + output) */
  tokens_used: number
  /** Estimated cost in USD */
  cost_usd: number
}

/**
 * Options for the description generation function
 */
export interface GenerationOptions {
  /** Public URL to the artwork image */
  image_url: string
  /** Artwork metadata for context */
  metadata: ArtworkMetadata
  /** Whether to include FR/JA translations (default: true) */
  include_translations?: boolean
}

/**
 * Entry for the ai_generation_log table
 */
export interface GenerationLogEntry {
  artwork_id: string
  generation_type: 'single' | 'bulk' | 'regenerate'
  prompt_version: string
  tokens_used?: number
  cost_usd?: number
  processing_time_ms?: number
  success: boolean
  error_message?: string
  generated_description?: string
  confidence_score?: number
}

/**
 * API request body for generating a description
 */
export interface GenerateDescriptionRequest {
  image_url: string
  metadata: ArtworkMetadata
  options?: {
    regenerate?: boolean
    include_translations?: boolean
  }
}

/**
 * API response for generate description endpoint
 */
export interface GenerateDescriptionResponse {
  success: boolean
  data?: GenerationResult
  error?: {
    code: string
    message: string
    details?: unknown
  }
  metadata?: {
    tokens_used: number
    estimated_cost_usd: number
    processing_time_ms: number
    prompt_version: string
  }
}

/**
 * API request body for applying generated description
 */
export interface ApplyDescriptionRequest {
  description: string
  short_description: string
  seo_title: string
  alt_text: string
  tags: string[]
  confidence_score: number
  translations: {
    fr: TranslatedContent
    ja: TranslatedContent
  }
}

/**
 * API response for apply description endpoint
 */
export interface ApplyDescriptionResponse {
  success: boolean
  data?: {
    artwork_id: string
    updated_fields: string[]
    tags_applied: number
  }
  error?: {
    code: string
    message: string
    details?: unknown
  }
}
